package com.rahmatullahsaruk.stock_management.service;

import com.rahmatullahsaruk.stock_management.entity.Invoice;
import com.rahmatullahsaruk.stock_management.entity.Product;
import com.rahmatullahsaruk.stock_management.repository.InvoiceRepo;
import com.rahmatullahsaruk.stock_management.repository.ProductRepo;
import jakarta.transaction.Transactional;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

@Service
public class InvoiceService {

    @Autowired
    private InvoiceRepo invoiceRepo;

    @Autowired
    private ProductRepo productRepo;

    @Transactional
    public Invoice save(Invoice invoice) {

        // Stock and snapshot logic ONLY for new invoices (Creation)
        if (invoice.getId() == null) {
            List<Product> soldProducts = new ArrayList<>();
            // Use a copy to iterate because we are replacing the list on the invoice
            List<Product> incomingProducts = new ArrayList<>(invoice.getProducts());

            // Clear the original list to be replaced with new snapshots
            invoice.getProducts().clear();

            for (Product incomingProduct : incomingProducts) {
                // The ID on the incomingProduct refers to the stock item ID
                Long stockProductId = incomingProduct.getId();

                // 1. Fetch the actual product from the database (the stock item)
                Product stockProduct = productRepo.findById(stockProductId)
                        .orElseThrow(() -> new RuntimeException("Product not found with id: " + stockProductId));

                // 2. Deduct stock quantity
                int soldQuantity = incomingProduct.getQuantity();
                int newQuantity = stockProduct.getQuantity() - soldQuantity;
                if (newQuantity < 0) {
                    throw new RuntimeException("Not enough stock for product: " + stockProduct.getName());
                }
                stockProduct.setQuantity(newQuantity);
                productRepo.save(stockProduct); // Save updated stock

                // 3. Create a SNAPSHOT product for the invoice line item
                Product sold = new Product();

                // IMPORTANT: Do NOT set ID or the invoice will try to treat this as an existing entity.
                // The new ID will be generated by the database when the Invoice is saved.

                // Snapshot properties from the stock item
                sold.setName(stockProduct.getName());
                sold.setDetails(stockProduct.getDetails());
                sold.setPrice(stockProduct.getPrice());

                // Set sold quantity
                sold.setQuantity(soldQuantity);

                // Set the back-reference (though mapper already did, good practice)
                sold.setInvoice(invoice);

                soldProducts.add(sold);
            }

            // Set the final list of new snapshot products to the invoice
            invoice.setProducts(soldProducts);
        }

        // --- Shared logic for both Create and Update ---

        // Set defaults if needed
        if (invoice.getDate() == null) {
            invoice.setDate(LocalDateTime.now());
        }

        if (invoice.getInvoiceNumber() == null || invoice.getInvoiceNumber().isBlank()) {
            invoice.setInvoiceNumber("INV-" + System.currentTimeMillis());
        }

        // Auto-calculate subtotal, tax, total (runs for both create and update)
        invoice.calculateTotals();

        return invoiceRepo.save(invoice);
    }

    public List<Invoice> getAll() {
        return invoiceRepo.findAll();
    }

    public Optional<Invoice> getById(Long id) {
        return invoiceRepo.findById(id);
    }

    public void delete(Long id) {
        invoiceRepo.deleteById(id);
    }
}