// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkac9-4nP12tFK9iBvCrZ2_ZyQ2YFIG2c',
    appId: '1:126442463674:web:11fefcccd2feff844d7d83',
    messagingSenderId: '126442463674',
    projectId: 'tstapp9-bf6e0',
    authDomain: 'tstapp9-bf6e0.firebaseapp.com',
    storageBucket: 'tstapp9-bf6e0.firebasestorage.app',
    measurementId: 'G-1ZP1XH34H5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk3KnAg9t6fQ7C9ncwlf7SMCC0g_mHAJY',
    appId: '1:126442463674:android:61720ca2e9dd97884d7d83',
    messagingSenderId: '126442463674',
    projectId: 'tstapp9-bf6e0',
    storageBucket: 'tstapp9-bf6e0.firebasestorage.app',
  );
}
