// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU5oGEpN6My5UvDHe0CQyfmgCQcAZRPtA',
    appId: '1:360569286344:web:911bea0e38913420583ffd',
    messagingSenderId: '360569286344',
    projectId: 'softvance-7d0f0',
    authDomain: 'softvance-7d0f0.firebaseapp.com',
    storageBucket: 'softvance-7d0f0.firebasestorage.app',
    measurementId: 'G-NSJJ1QZKBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRjqDVbKQ2sqgKhr4PfoS_ZWZ5eOMWilA',
    appId: '1:360569286344:android:47decc9e1b941968583ffd',
    messagingSenderId: '360569286344',
    projectId: 'softvance-7d0f0',
    storageBucket: 'softvance-7d0f0.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDU5oGEpN6My5UvDHe0CQyfmgCQcAZRPtA',
    appId: '1:360569286344:web:aa4e299f8f57e301583ffd',
    messagingSenderId: '360569286344',
    projectId: 'softvance-7d0f0',
    authDomain: 'softvance-7d0f0.firebaseapp.com',
    storageBucket: 'softvance-7d0f0.firebasestorage.app',
    measurementId: 'G-W9CWJM2K9Z',
  );
}
